# Generated by nixos-generate-config on the target machine.
# Replace this file with the output of:
#   nixos-generate-config --show-hardware-config
{ config, lib, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot.initrd.availableKernelModules = [ "virtio_pci" "virtio_blk" ];
  boot.kernelModules = [ ];

  fileSystems."/" = {
    device = "/dev/vda1";
    fsType = "ext4";
  };

  swapDevices = [ ];
}
